common: &shared
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  username: root
  password: root
  
development:
  database: cms_development
  <<: *shared
  
test:
  database: cms_test
  <<: *shared

production:
  database: cms_production
  <<: *shared